# Generated by Django 2.0 on 2017-12-18 21:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=200, verbose_name='Nome do Curso')),
                ('data_inicio_oferta', models.DateField(default=django.utils.timezone.now, verbose_name='Data de início da oferta')),
                ('carga_horaria', models.IntegerField(default=2400, verbose_name='Carga Horária')),
                ('modalidade', models.CharField(choices=[('PRE', 'Presencial'), ('EAD', 'Ensino à distância')], default='PRE', max_length=3)),
                ('nivel_curso', models.CharField(choices=[('BACH', 'Bacharelado'), ('LICEN', 'Licenciatura'), ('TEC', 'Técnico'), ('NAP', 'Não Aplicável')], default='BACH', max_length=5)),
                ('periodo', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno'), ('I', 'Integral'), ('VN', 'Vespertino/Noturno')], default='N', max_length=2)),
                ('curso_gratuito', models.BooleanField(default=True, verbose_name='Curso Gratuito')),
                ('num_vagas', models.IntegerField(default=40, verbose_name='Número de vagas')),
                ('possui_acessabilidade', models.BooleanField(default=False, verbose_name='Possui Acessabilidade')),
            ],
        ),
        migrations.CreateModel(
            name='IntituicaoEnsinoSuperior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_IES', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla_IES', models.CharField(max_length=10, verbose_name='Sigla')),
                ('email_IES', models.CharField(max_length=32, verbose_name='Email')),
                ('organizacao_academica', models.CharField(choices=[('UNI', 'Universidade'), ('CENT_UNI', 'Centro Universitário'), ('FACUL', 'Faculdade'), ('INST_FED', 'Instituto Federal')], default='UNI', max_length=10, verbose_name='Organização Acadêmica')),
                ('rede', models.CharField(choices=[('PUB', 'Pública'), ('PRI', 'Privada')], default='PUB', max_length=3, verbose_name='Rede')),
                ('departamento_administrativo', models.CharField(choices=[('FED', 'Federal'), ('EST', 'Estadual'), ('MUN', 'Municipal'), ('PRI', 'Privada')], default='EST', max_length=3, verbose_name='Departamento Administrativo')),
                ('cep', models.IntegerField(default=0, verbose_name='CEP')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenedora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mant', models.CharField(max_length=80, verbose_name='Nome: ')),
            ],
        ),
        migrations.AddField(
            model_name='intituicaoensinosuperior',
            name='cod_mant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Mantenedora'),
        ),
        migrations.AddField(
            model_name='curso',
            name='cod_IES',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.IntituicaoEnsinoSuperior'),
        ),
    ]
